version: '3'
services:
  xivlm:
    container_name: xiv-mitm-latency-mitigator
    image: bankja/xivlm:latest
    environment:
      - MITIGATOR=true # Default to true. Set to false when need to disable XivMitmLatencyMitigator script.
      # - DEFINITIONS_URL=https://pastebin.com/raw/jf66WP69 # URL of 6.38 definitions.json.
      - LOCAL=true # Default to true. Set to false when not use within LAN (E.g. Connect through VPN only).
      - LEGACY=false # Default to false. Set to true if you want to use iptables-legacy.
      - VPN=false # Default to false. Set to true if you use this on private VPN server.
      - VPN_INTERFACE_1=wg0 # Find by using "ip a" command.
      # - VPN_INTERFACE_2=wg1
      # - VPN_INTERFACE_3=<Add many VPN interfaces as you want.>
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
